version: '3.9'

services:
  integration_tests:
    container_name: integration_tests
    build:
      context: ../
      dockerfile: ./build/integrationTests/Dockerfile
    env_file:
    - ../configs/dc/config.env
    depends_on:
       mysql-db:
        condition: service_healthy
       redis:
        condition: service_started
       antibruteforce:
        condition: service_started
    volumes:
      - "./configs:/app/configs"
    networks:
    - ab_network