linters:
  # Disable all linters.
  # Default: false

  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default

 
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
     - ifshort
     - scopelint
     - nosnakecase
     - lll
     - dupl
     - gci
     - usestdlibvars
     - testpackage
     - gomnd
     - gochecknoglobals
     - interfacebloat
     - forbidigo
     - gochecknoinits
     - wsl
     - whitespace
     - goconst
     - funlen
     - gocognit


    
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true