File: .github/workflows/abworkflow.yml
name: ABworkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: make build

    - name: Install golint
      run: make install-lint-deps

    - name: Run golint
      run: make lint

    - name: Run tests
      run: make test