name: goworkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO111MODULE: "on"
  working-directory: .

jobs:
  goworkflow:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
   #   with:
   #     GITHUB_TOKEN: ${{ secrets.GO_AB }}
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4
    
    - name: Download dependencies
      run: go mod download   

   # - name: Verify dependencies
   #   run: go mod verify

    - name: Build
      run: make build

    - name: Install golint
      run: make install-lint-deps

    - name: Run golint
      run: make lint

    - name: Run tests
      run: make test